import assert from 'node:assert/strict';
import { FlipperInput } from '../src/flipper-input.ts';

const input = new FlipperInput();
input.press('touch-left', 0, 100); input.press('touch-right', 1, 103);
assert.deepEqual(input.at(140), [true, true], 'two thumbs can hold both paddles beyond the minimum stroke');
input.release('touch-left');
assert.deepEqual(input.at(141), [false, true], 'release one paddle for aiming while the other stays held');
input.press('touch-left', 0, 145); input.release('touch-left');
assert.deepEqual(input.at(154), [true, true], 'a quick release-and-shoot retains the accepted ten-tick stroke');
assert.deepEqual(input.at(155), [false, true], 'the tap ends at the original tick boundary');
input.press('KeyL', 1, 155); input.release('touch-right');
assert.deepEqual(input.at(180), [false, true], 'lifting a thumb does not clear a simultaneous keyboard hold');
assert.equal(input.press('KeyL', 1, 180), false, 'repeat keydown does not retrigger the stroke');
input.release('KeyL'); assert.deepEqual(input.at(181), [false, false]);
input.press('touch-cancel', 0, 190); input.cancel('touch-cancel');
assert.deepEqual(input.at(191), [false, false], 'cancellation clears an unfinished touch stroke immediately');
input.press('touch-left', 0, 200); input.press('touch-left-second-finger', 0, 202); input.cancel('touch-left');
assert.deepEqual(input.at(240), [true, false], 'cancelling one finger preserves another finger on the same paddle');
input.clear(); assert.deepEqual(input.at(241), [false, false], 'pause/tab loss clears all fingers, keys and pending strokes');
input.release('unknown'); input.cancel('unknown'); assert.deepEqual(input.at(241), [false, false]);
input.press('touch-new-round', 1, 0); input.release('touch-new-round');
assert.deepEqual(input.at(9), [false, true], 'a fresh match accepts taps after the simulation tick resets');
assert.deepEqual(input.at(10), [false, false]);
const upper = new FlipperInput(12);
assert.equal(upper.press('Space', 0, 0), true, 'Space starts the shared upper input');
assert.equal(upper.at(600)[0], true, 'holding Space keeps both upper paddles extended beyond the minimum stroke');
assert.equal(upper.press('Space', 0, 600), false, 'keyboard repeat does not retrigger a held upper stroke');
upper.press('pointer', 0, 601); upper.release('Space');
assert.equal(upper.at(700)[0], true, 'a pointer hold survives Space release');
upper.release('pointer'); assert.equal(upper.at(701)[0], false, 'the last upper source releases both paddles');
upper.press('tap', 0, 710); upper.release('tap');
assert.equal(upper.at(721)[0], true, 'a short upper tap gets twelve ticks to complete its stroke');
assert.equal(upper.at(722)[0], false, 'the upper tap retracts after its minimum stroke');
upper.press('cancel', 0, 730); upper.cancel('cancel'); assert.equal(upper.at(731)[0], false, 'pointer cancellation clears a pending upper tap');
upper.press('Space', 0, 740); upper.clear(); assert.equal(upper.at(741)[0], false, 'pause or focus loss clears every upper hold');
console.log('22 input checks passed: lower and upper holds, minimum taps, mixed sources, cancellation and reset.');
