import assert from 'node:assert/strict';
import { FlipperInput } from '../src/flipper-input.ts';

const input = new FlipperInput();
input.press('touch-left', 0, 100); input.press('touch-right', 1, 103);
assert.deepEqual(input.at(140), [true, true], 'two thumbs can hold both paddles beyond the minimum stroke');
input.release('touch-left');
assert.deepEqual(input.at(141), [false, true], 'release one paddle for aiming while the other stays held');
input.press('touch-left', 0, 145); input.release('touch-left');
assert.deepEqual(input.at(154), [true, true], 'a quick release-and-shoot retains the accepted ten-tick stroke');
assert.deepEqual(input.at(155), [false, true], 'the tap ends at the original tick boundary');
input.press('KeyL', 1, 155); input.release('touch-right');
assert.deepEqual(input.at(180), [false, true], 'lifting a thumb does not clear a simultaneous keyboard hold');
assert.equal(input.press('KeyL', 1, 180), false, 'repeat keydown does not retrigger the stroke');
input.release('KeyL'); assert.deepEqual(input.at(181), [false, false]);
input.press('touch-cancel', 0, 190); input.cancel('touch-cancel');
assert.deepEqual(input.at(191), [false, false], 'cancellation clears an unfinished touch stroke immediately');
input.press('touch-left', 0, 200); input.press('touch-left-second-finger', 0, 202); input.cancel('touch-left');
assert.deepEqual(input.at(240), [true, false], 'cancelling one finger preserves another finger on the same paddle');
input.clear(); assert.deepEqual(input.at(241), [false, false], 'pause/tab loss clears all fingers, keys and pending strokes');
input.release('unknown'); input.cancel('unknown'); assert.deepEqual(input.at(241), [false, false]);
input.press('touch-new-round', 1, 0); input.release('touch-new-round');
assert.deepEqual(input.at(9), [false, true], 'a fresh match accepts taps after the simulation tick resets');
assert.deepEqual(input.at(10), [false, false]);
console.log('13 input checks passed: simultaneous thumbs, aiming release, minimum taps, mixed inputs, cancellation and reset.');
